apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-oi6v
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-oi6v
    app.kubernetes.io/part-of: ci10t-777-0067-app
  name: devfile-sample-oi6v
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-oi6v
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-oi6v
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0067-tenant/ci10t-777-0067-app/devfile-sample-oi6v@sha256:a81c2bfff5e71435d97cda6e72440ee581da3d44220f737ca467aea5b243ebc9
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
